### ISSUE TITLE
Access to documentation

### ISSUE THREAD

**Issue by pa-w** [creativecommons/paola-onboarding#2]
I need access to the current documentation for the following items:

- CC Search development and deployment 
- Web services deployment
- Servers/Infrastructure

Or anything else you think would be useful.

**Comment by robmyers** [comment]
I have shared the (minimal) documentation I have with you, I will write up something better for web service deployment and server infrastructure this afternoon.

**Comment by pa-w** [comment]
Thanks a lot, @robmyers! :)
